name: news
description: News App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^1.1.0
  webview_flutter: ^4.4.1
  share_plus: ^7.2.1
  intl: ^0.18.1
  dynamic_color: ^1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true